"""
Output formatters: Markdown, JSON, plain text.
"""

import json
from .fetcher import RepoData


def to_json(analysis: dict, indent: int = 2) -> str:
    return json.dumps(analysis, indent=indent, ensure_ascii=False)


def to_markdown(repo: RepoData, analysis: dict) -> str:
    stars = f"{repo.stars:,}"
    forks = f"{repo.forks:,}"
    difficulty_emoji = {"beginner": "🟢", "intermediate": "🟡", "advanced": "🔴"}.get(
        analysis.get("difficulty", "").lower(), "⚪"
    )

    lines = [
        f"# repo-xray report: [{repo.full_name}]({repo.url})",
        "",
        f"> ⭐ {stars} stars  |  🍴 {forks} forks  |  {difficulty_emoji} {analysis.get('difficulty','').capitalize()}",
        "",
        "---",
        "",
        "## What is this?",
        "",
        analysis.get("summary", ""),
        "",
        "## Tech Stack",
        "",
    ]
    for tech in analysis.get("tech_stack", []):
        lines.append(f"- `{tech}`")

    lines += [
        "",
        "## Architecture",
        "",
        analysis.get("architecture", ""),
        "",
        "## Key Files",
        "",
    ]
    for kf in analysis.get("key_files", []):
        lines.append(f"- **`{kf['path']}`** — {kf['role']}")

    lines += [
        "",
        "## Learning Insights",
        "",
    ]
    for i, insight in enumerate(analysis.get("learning_insights", []), 1):
        lines.append(f"**{i}.** {insight}")
        lines.append("")

    lines += [
        "## AI Rebuild Prompt",
        "",
        "> Copy this prompt into any AI coding agent to recreate the project.",
        "",
        "```",
        analysis.get("ai_rebuild_prompt", ""),
        "```",
        "",
        "## Quick Start Guide",
        "",
        analysis.get("quick_start_guide", ""),
        "",
        "## Explore More",
        "",
    ]
    for s in analysis.get("similar_projects", []):
        lines.append(f"- {s}")

    lines += [
        "",
        "---",
        "",
        f"**Fun fact:** {analysis.get('fun_fact', '')}",
        "",
        f"*Generated by [repo-xray](https://github.com/teyfikoz/repo-xray)*",
    ]
    return "\n".join(lines)


def to_plain(repo: RepoData, analysis: dict) -> str:
    sep = "=" * 60
    lines = [
        sep,
        f"REPO-XRAY REPORT: {repo.full_name}",
        sep,
        "",
        f"SUMMARY",
        "-" * 40,
        analysis.get("summary", ""),
        "",
        f"TECH STACK: {', '.join(analysis.get('tech_stack', []))}",
        f"DIFFICULTY: {analysis.get('difficulty', '').upper()}",
        f"STARS: {repo.stars:,} | FORKS: {repo.forks:,}",
        "",
        "ARCHITECTURE",
        "-" * 40,
        analysis.get("architecture", ""),
        "",
        "LEARNING INSIGHTS",
        "-" * 40,
    ]
    for i, insight in enumerate(analysis.get("learning_insights", []), 1):
        lines.append(f"{i}. {insight}")
    lines += [
        "",
        "AI REBUILD PROMPT",
        "-" * 40,
        analysis.get("ai_rebuild_prompt", ""),
        "",
        "QUICK START",
        "-" * 40,
        analysis.get("quick_start_guide", ""),
        "",
        f"FUN FACT: {analysis.get('fun_fact', '')}",
        "",
        sep,
    ]
    return "\n".join(lines)
